# as documented here https://gitlab.gwdg.de/gfbio/cicd :
include:
  - project: gfbio/cicd
    file:
      - '.create_merge_request_v3.yml'
      - '.web_test_v2.yml'
      - '.tag_release.yml'

# TODO: unit-tests is conflicting with release, since both currently run on the same machine and cause errors when using the same docker network
#  - unit_tests
stages:
  - create_merge_request
  - tag_release_check
  - tag_release
  - web_test_check
  - web_test_update
  - web_test_stop


#run_unit_tests:
#  stage: unit_tests
#  before_script:
#    - sudo rm -rf .pytest_cache
#    - rsync -a /home/gitlab-runner/.envs .
#    - docker-compose -f local.yml build
#    # - docker-compose -f local.yml run --rm django python manage.py migrate
#  script:
#    - docker-compose -f local.yml run django pytest
#  after_script:
#    - sudo rm -rf .pytest_cache
#  tags:
#    - gfbio-dmp-prod

create_merge_request:
  variables:
    PROJECT_NAME: "gfbio-dmp"
  tags:
    - dev-denbi

tag_release_check:
  variables:
    MAIN_BRANCH_NAME: "master"
  tags:
    - dev-denbi

tag_release:
  script:
    - rsync -a /home/gitlab-runner/.envs .
    - docker-compose -f production.yml down
    - docker-compose -f production.yml build
    - docker-compose -f production.yml up -d postgres
    - docker-compose -f production.yml run --rm postgres backup
    - docker-compose -f production.yml run --rm django python manage.py migrate
    # - TODO: add js built and copy commands here
    - docker-compose -f production.yml run --rm django python manage.py collectstatic --noinput
    - docker-compose -f production.yml down
    - docker-compose -f production.yml up -d
  environment:
    name: production
    url: https://dmp.gfbio.dev
  tags:
    - gfbio-dmp-prod

# ------------------------- WEBTEST ---------------------------
# add your commands under "your custom commands" section
# example: 123-foo-bar with project name ammod will create stack named 123-ammod
# in this example you can also see how to get ISSUE_ID from branch
# PROJECT_NAME - should be specified, default is project-id
# COMPOSE_FILE - should be specified, default is production.yml
web_test_update:
  variables:
    PROJECT_NAME: "gfbio-dmp"
    COMPOSE_FILE: "web-test.yml"
  script:
    # get issue id and test name
    - ISSUE_ID=$(awk -F- '{print $1}' <<< ${CI_COMMIT_REF_NAME})
    - TEST_NAME=$ISSUE_ID-$PROJECT_NAME
    # your custom commands
    - rm -r ./.envs/
    - cp -r /home/gitlab-runner/.gfbio_dmp_envs/ ./.envs/
    - sed -i s/DJANGO_ALLOWED_HOSTS=.*/DJANGO_ALLOWED_HOSTS=\.$TEST_NAME\.test.gfbio\.dev/g .envs/.production/.django
    - sed -i s/BRANCH/${TEST_NAME}/g $COMPOSE_FILE
    # remove email verification requirements from web-test
    - sed -i 's/ACCOUNT_EMAIL_VERIFICATION = "mandatory"/ACCOUNT_EMAIL_VERIFICATION = "none"/g' config/settings/base.py
    # set super user credentials from GitLab CI/CD Variables
    - sed -i s/ADMIN_NICKNAME=/ADMIN_NICKNAME=${ADMIN_NICKNAME}/g ./compose/production/django/ci_start
    - sed -i s/ADMIN_EMAIL=/ADMIN_EMAIL=${ADMIN_EMAIL}/g ./compose/production/django/ci_start
    - sed -i s/ADMIN_PASSWORD=/ADMIN_PASSWORD=${ADMIN_PASSWORD}/g ./compose/production/django/ci_start
    # TODO: add dmpt-app specific build and copy commands
    #    - cd ammod_ui && npm i && npm run collect
    #    - cd ../
    - docker-compose -f $COMPOSE_FILE build
    # run docker stack
    - docker stack rm $TEST_NAME || true
    - while [[ $(docker ps | grep $TEST_NAME | wc -l) > 0 ]]; do sleep 1; done
    - docker stack deploy -c $COMPOSE_FILE $TEST_NAME

# will stop running environmnet
web_test_stop:
  variables:
    MAIN_BRANCH_NAME: "master"
    PROJECT_NAME: "gfbio-dmp"
