# according to https://gitlab.gwdg.de/gfbio/cicd -------------------------------
# TODO: unit-tests is conflicting with release, since both currently run on the same machine and cause errors when using the same docker network
#  - unit_tests
include:
  - project: gfbio/cicd
    file:
      - '.create_merge_request.yml'
      - '.tag_release.yml'

stages:
  - create_merge_request
  - tag_release_check
  - tag_release

run_unit_tests:
  stage: unit_tests
  before_script:
    - sudo rm -rf .pytest_cache
    - rsync -a /home/gitlab-runner/.envs .
    - docker-compose -f local.yml build
    # FIXME: currently not possible due to misssing migration in rdmo questions
    # - docker-compose -f local.yml run --rm django python manage.py migrate
  script:
    - docker-compose -f local.yml run django pytest
  after_script:
    - echo "after_script.. remove ?"
    - sudo rm -rf .pytest_cache
    - echo "after_script.. remove ?"
  tags:
    - gfbio-dmpt-dev

create_merge_request:
  tags:
    - gfbio-dmpt-dev

tag_release_check:
  variables:
    MAIN_BRANCH_NAME: "master"
  tags:
    - gfbio-dmpt-dev

tag_release:
  script:
    - rsync -a /home/gitlab-runner/.envs .
    - docker-compose -f production.yml down
    - docker-compose -f production.yml build
    - docker-compose -f production.yml up -d postgres
    - docker-compose -f production.yml run --rm postgres backup
    - docker-compose -f production.yml run --rm django python manage.py migrate
    - docker-compose -f production.yml run --rm django python manage.py collectstatic
    - docker-compose -f production.yml down
    - docker-compose -f production.yml up -d
  environment:
    name: production
    url: https://dmp.gfbio.dev
  tags:
    - gfbio-dmpt-dev
