version: '3'

volumes:
  local_postgres_data: { }
  local_postgres_data_backups: { }

networks:
  local_default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: gfbio_dmpt_local_django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    networks:
      - local_default
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: gfbio_dmpt_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - local_default

  docs:
    image: gfbio_dmpt_local_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    networks:
      - local_default
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./gfbio_dmpt:/app/gfbio_dmpt:z
    ports:
      - "7000:7000"
    command: /start-docs

  redis:
    image: redis:5.0
    container_name: redis

  celeryworker:
    <<: *django
    image: gfbio_dmpt_local_celeryworker
    container_name: celeryworker
    depends_on:
      - redis
      - postgres
    networks:
      - local_default
    ports: [ ]
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: gfbio_dmpt_local_celerybeat
    container_name: celerybeat
    depends_on:
      - redis
      - postgres
    ports: [ ]
    networks:
      - local_default
    command: /start-celerybeat

  flower:
    <<: *django
    image: gfbio_dmpt_local_flower
    container_name: flower
    networks:
      - local_default
    ports:
      - "5555:5555"
    command: /start-flower
