# Generated by Django 3.2.5 on 2022-03-24 10:54

from django.db import migrations
import django.utils.timezone
import gfbio_dmpt.generic.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211020_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=gfbio_dmpt.generic.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='user',
            name='modified',
            field=gfbio_dmpt.generic.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
