# Generated by Django 3.2.5 on 2021-11-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira_integration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dmpjirastatus',
            old_name='project_id',
            new_name='project',
        ),
    ]
