# Generated by Django 3.2.5 on 2021-11-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_value_set_prefix'),
        ('jira_integration', '0002_rename_project_id_dmpjirastatus_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DmpJiraStatus',
            new_name='Ticket',
        ),
    ]
