# Generated by Django 3.2.5 on 2021-11-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_value_set_prefix'),
        ('jira_integration', '0005_alter_ticket_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='JiraTicket',
        ),
    ]
