# Generated by Django 3.2.5 on 2021-11-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_value_set_prefix'),
        ('jira_integration', '0006_rename_ticket_jiraticket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JiraTicket',
            new_name='Ticket',
        ),
    ]
