#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
python /app/manage.py migrate

ADMIN_NICKNAME=
ADMIN_EMAIL=
ADMIN_PASSWORD=

python /app/manage.py shell << EOF
from django.contrib.auth import get_user_model;
User = get_user_model();
User.objects.create_superuser("${ADMIN_NICKNAME}", "${ADMIN_EMAIL}", "${ADMIN_PASSWORD}")
EOF

python /app/manage.py loaddata /app/web-test-data.json

compress_enabled() {
python << END
import sys

from environ import Env

env = Env(COMPRESS_ENABLED=(bool, True))
if env('COMPRESS_ENABLED'):
    sys.exit(0)
else:
    sys.exit(1)

END
}

if compress_enabled; then
  # NOTE this command will fail if django-compressor is disabled
  python /app/manage.py compress
fi


/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app