log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"
    forwardedHeaders:
      trustedIPs:
        - "192.168.0.216/32"

  web-secure:
    # https
    address: ":443"

  flower:
    address: ":5555"


https://gitlab-pe:
  gwdg:
    de/gfbio/dmp:
      org:
        git:

http:
  routers:
    web-secure-router:
      rule: "Host(`dmp.gfbio.dev`) || Host(`dmp.gfbio.org`)"
      entryPoints:
        - web
      middlewares:
        - csrf
      service: django

    flower-secure-router:
      rule: "Host(`dmp.gfbio.dev`) || Host(`dmp.gfbio.org`)"
      entryPoints:
        - flower
      service: flower

  middlewares:
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: [ "X-CSRFToken" ]

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
