# Generated by Django 3.2.5 on 2022-01-13 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_value_set_prefix'),
        ('gfbio_dmpt_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmptproject',
            name='rdmo_project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
