# Generated by Django 3.2.5 on 2022-05-25 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gfbio_dmpt_form', '0003_dmptissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmptissue',
            name='dmpt_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='gfbio_dmpt_form.dmptproject'),
        ),
    ]
