# Generated by Django 3.2.16 on 2024-06-18 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0068_meta'),
        ('gfbio_dmpt_form', '0004_alter_dmptissue_dmpt_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='DmptCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('catalog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.catalog')),
            ],
        ),
    ]
